Name = input("Enter Name: ")
print(f"Name = {Name}")
print(Name, 'is of type', type(Name))
print()
print()
age = int(input("Enter age: "))
print(f"Age = {age} years")
print(age, 'is of type', type(age))
print()
Height = float(input("Enter height in feet: "))
print(f"Height = {Height} feet")
print(Height, 'is of type', type(Height))
print()
